### ISSUE TITLE
Doesn't seem to be compatible with ArchivesSpace v2.6.0 

### ISSUE THREAD

**Issue by sdm7g** [umd-lib/umd_aeon_fulfillment#7]
Doesn't seem to be compatible with ArchivesSpace v2.6.0 
Even after fixing the font-awesome issue, still not working. 
Investigating...

**Comment by ghost** [comment]
FYI, we are currently using this plugin with ArchivesSpace v2.5.1

**Comment by sdm7g** [comment]
We also had no problems on 2.5.2. Problems appeared after upgrading to 2.6.0. 
We then updated Atlas System's aeon_fullfillmet_plugin with 2.6.0 fixes. That works with UMD plugin disabled, but enabling UMD plugin stops everything from working. That's how we're currently running.  

```
I, [2019-09-05T21:23:41.454166 #30555]  INFO -- : [d807b350-49fb-4402-82a5-21323f20da3f]   Rendered /usr/local/projects/archivesspace/plugins/umd_aeon_fulfillment/public/views/containers/show.html.erb within layouts/application (7.3ms)
I, [2019-09-05T21:23:41.454527 #30555]  INFO -- : [d807b350-49fb-4402-82a5-21323f20da3f] Completed 500 Internal Server Error in 58ms
F, [2019-09-05T21:23:41.456341 #30555] FATAL -- : [d807b350-49fb-4402-82a5-21323f20da3f]   
F, [2019-09-05T21:23:41.456457 #30555] FATAL -- : [d807b350-49fb-4402-82a5-21323f20da3f] ActionView::Template::Error (undefined method `reject' for nil:NilClass):
F, [2019-09-05T21:23:41.456648 #30555] FATAL -- : [d807b350-49fb-4402-82a5-21323f20da3f]     1: <%
[d807b350-49fb-4402-82a5-21323f20da3f]     2: mapper = AeonRecordMapper.mapper_for(@result)
[d807b350-49fb-4402-82a5-21323f20da3f]     3: %>
[d807b350-49fb-4402-82a5-21323f20da3f]     4: 
[d807b350-49fb-4402-82a5-21323f20da3f]     5: <div id="main-content" class="containers">
F, [2019-09-05T21:23:41.456735 #30555] FATAL -- : [d807b350-49fb-4402-82a5-21323f20da3f]   
F, [2019-09-05T21:23:41.456850 #30555] FATAL -- : [d807b350-49fb-4402-82a5-21323f20da3f] /usr/local/projects/archivesspace/plugins/aeon_fulfillment/public/models/aeon_record_mapper.rb:410:in `find_container_instances'
[d807b350-49fb-4402-82a5-21323f20da3f] /usr/local/projects/archivesspace/plugins/aeon_fulfillment/public/models/aeon_record_mapper.rb:11:in `initialize'
[d807b350-49fb-4402-82a5-21323f20da3f] /usr/local/projects/archivesspace/plugins/umd_aeon_fulfillment/public/models/aeon_container_mapper.rb:5:in `initialize'
[d807b350-49fb-4402-82a5-21323f20da3f] /usr/local/projects/archivesspace/plugins/aeon_fulfillment/public/models/aeon_record_mapper.rb:24:in `mapper_for'
[d807b350-49fb-4402-82a5-21323f20da3f] /usr/local/projects/archivesspace/plugins/umd_aeon_fulfillment/public/views/containers/show.html.erb:2:in `__usr_local_projects_archivesspace_plugins_umd_aeon_fulfillment_public_views_containers_show_html_erb___1747020087_2714'
[d807b350-49fb-4402-82a5-21323f20da3f] actionview (5.0.7.2) lib/action_view/template.rb:159:in `block in render'
[d807b350-49fb-4402-82a5-21323f20da3f] activesupport (5.0.7.2) lib/active_support/notifications.rb:166:in `instrument'
[d807b350-49fb-4402-82a5-21323f20da3f] actionview (5.0.7.2) lib/action_view/template.rb:354:in `instrument'
[d807b350-49fb-4402-82a5-21323f20da3f] actionview (5.0.7.2) lib/action_view/template.rb:157:in `render'
```

**Comment by sdm7g** [comment]
I don't know if this is _the_ solution, but trying to catch the site of the crash in the [Atlas Systems plugin](https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/blob/master/public/models/aeon_record_mapper.rb#L410) I changed that line:

```
instances = record_json['instances']
            .reject { |instance| instance['digital_object'] }
```

to 

```
instances = record_json.fetch('instances', [] )
            .reject { |instance| instance['digital_object'] }
```

and it appears to work now.  
( i.e. it returns a value and doesn't crash -- I haven't yet verified if it's working the same as previously and returning the same values.  I'm not yet very familiar with the models in both plugins, so I'm not confident that I understand why it broke in updates or if that is the best place to fix it or not. )
